// https://github.com/EvanOverman/Auto-Web-Server
// This file was generated by Auto-Web-Server
express = require('express');
path = require('path');
app = express();
app.get('/GS-Compatable', (req,res) => {
	res.send(path.join(__dirname + '/GS-Compatable'));
	console.log('server got request for /GS-Compatable ... ');
});
app.get('/LICENSE', (req,res) => {
	res.send(path.join(__dirname + '/LICENSE'));
	console.log('server got request for /LICENSE ... ');
});
app.get('/Organized', (req,res) => {
	res.send(path.join(__dirname + '/Organized'));
	console.log('server got request for /Organized ... ');
});
app.get('/README.md', (req,res) => {
	res.send(path.join(__dirname + '/README.md'));
	console.log('server got request for /README.md ... ');
});
app.get('/Simple', (req,res) => {
	res.send(path.join(__dirname + '/Simple'));
	console.log('server got request for /Simple ... ');
});
app.get('/Standard', (req,res) => {
	res.send(path.join(__dirname + '/Standard'));
	console.log('server got request for /Standard ... ');
});
app.get('/a.out', (req,res) => {
	res.send(path.join(__dirname + '/a.out'));
	console.log('server got request for /a.out ... ');
});
app.get('/directoryIndex.ls', (req,res) => {
	res.send(path.join(__dirname + '/directoryIndex.ls'));
	console.log('server got request for /directoryIndex.ls ... ');
});
app.get('/directoryIndexing.h', (req,res) => {
	res.send(path.join(__dirname + '/directoryIndexing.h'));
	console.log('server got request for /directoryIndexing.h ... ');
});
app.get('/install.sh', (req,res) => {
	res.send(path.join(__dirname + '/install.sh'));
	console.log('server got request for /install.sh ... ');
});
app.get('/main.cpp', (req,res) => {
	res.send(path.join(__dirname + '/main.cpp'));
	console.log('server got request for /main.cpp ... ');
});
app.get('/node_modules', (req,res) => {
	res.send(path.join(__dirname + '/node_modules'));
	console.log('server got request for /node_modules ... ');
});
app.get('/package-lock.json', (req,res) => {
	res.send(path.join(__dirname + '/package-lock.json'));
	console.log('server got request for /package-lock.json ... ');
});
app.get('/server.js', (req,res) => {
	res.send(path.join(__dirname + '/server.js'));
	console.log('server got request for /server.js ... ');
});
app.get('/serverJS.h', (req,res) => {
	res.send(path.join(__dirname + '/serverJS.h'));
	console.log('server got request for /serverJS.h ... ');
});
app.get('/startMessage.txt', (req,res) => {
	res.send(path.join(__dirname + '/startMessage.txt'));
	console.log('server got request for /startMessage.txt ... ');
});
app.get('/', (req,res) => {
	res.send(path.join(__dirname + '/'));
	console.log('server got request for / ... ');
});
app.get('/', (req,res) => {
	res.send(path.join(__dirname + '/'));
	console.log('server got request for / ... ');
});
app.listen(6969, console.log('server listening on port 6969 ... '));
